version: '3'

services:
  mysql:
    image: mariadb:latest
    #image: mysql:8
    container_name: ${APP_NAME}-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: always
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:rw,delegated
      #- ./volumes/mysql:/var/lib/mysql:rw,delegated
  drupal:
    build: .
    container_name: ${APP_NAME}-drupal
    #ports:
    #  - 8083:80
    volumes:
      # copy local keys to docker image so docker container can access remote servers
      - ~/.ssh:/root/.ssh:ro
      - ./:/var/www
      - ./nn/docker-prod/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./nn/docker-prod/php.ini:/usr/local/etc/php/php.ini
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    labels:
      ## Traefik
      - "traefik.enable=true"

      # Set Hosts
      - "traefik.http.routers.${APP_NAME}-drupal.rule=Host(`${HOSTNAME}`)"
      # Example with multiple hosts
      # - "traefik.http.routers.${APP_NAME}-drupal.rule=Host(`${HOSTNAME}`) || Host(`live.domain.ch`)"

      # Other traefik configs
      #- "traefik.http.routers.${APP_NAME}-drupal.entryPoints=websecure"
      - "traefik.http.services.${APP_NAME}-drupal.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}-drupal.tls=true"
      - "traefik.http.routers.${APP_NAME}-drupal.tls.certresolver=leresolver"

      ## Configure redirects (example! Change according to your needs)
      #- "traefik.http.routers.${APP_NAME}-drupal.middlewares=nn-${APP_NAME}-redirector-1@docker,nn-${APP_NAME}-redirector-2@docker"
      # Redirect www.otherdomain.ch -> www.domain.ch
      #- "traefik.http.middlewares.nn-${APP_NAME}-redirector-1.redirectregex.regex=^(https://)(www\\.otherdomain\\.ch)(/.*)?"
      #- "traefik.http.middlewares.nn-${APP_NAME}-redirector-1.redirectregex.replacement=https://www.domain.ch$${3}"
      # Redirect otherdomain.ch -> www.domain.ch
      #- "traefik.http.middlewares.nn-${APP_NAME}-redirector-2.redirectregex.regex=^(https://)(.otherdomain\\.ch)(/.*)?"
      #- "traefik.http.middlewares.nn-${APP_NAME}-redirector-2.redirectregex.replacement=https://www.theater-basel.ch$${3}"
 

      ## Configure Basic Auth
      - "traefik.http.routers.${APP_NAME}-drupal.middlewares=nn-${APP_NAME}-auth"
      - "traefik.http.middlewares.nn-${APP_NAME}-auth.basicauth.users=netnode:$$apr1$$auekidRk$$VwltF9XdS4OPufteMwuCV1" # netnode/T3stdom@in
      
    env_file:
      - .env
    links:
      - mysql
    networks:
      - default
      - proxy


networks:
  proxy:
    external: true
    name: proxy

