version: '3'

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task -l

  nn-lando-start:
    desc: Start coding - composer install, sync db, start lando
    cmds:
      - ./nn/lando/nn_start.sh

  nn-lando-build-frontend:
    desc: Builds the frontend assets
    cmds:
      - ./nn/lando/nn_build_frontend.sh

  nn-lando-sync-db-prod:
    desc: Syncs the local database with the production database
    cmds:
      - ./nn/lando/nn_sync_db_prod.sh

  nn-lando-maintenance:
    desc: Puts the site into maintenance mode
    cmds:
      - ./nn/lando/nn_maintenance.sh

  nn-lando-open:
    desc: Opens the site in the default browser
    cmds:
      - ./nn/lando/nn_open.sh

  nn-open-bitbucket:
    desc: Opens the Bitbucket repository in the default browser
    cmds:
      - open https://bitbucket.org/NETNODEAG/example.ch

  nn-ssh-prod:
    desc: SSH into the production server
    cmds:
      - ssh netnode@prod.example.ch.netnode.cloud
    interactive: true

  nn-demo-install:
    desc: Installs the Drupal demo using PHP server
    cmds:
      - ./nn/demo/nn_demo_install.sh

  nn-demo-serve:
    desc: Serves the Drupal demo using PHP server
    cmds:
      - ./nn/demo/nn_demo_serve.sh

  nn-docker-sync-db-prod:
    desc: Syncs the local database with the production database using Docker
    cmds:
      - docker compose exec drupal sh -c 'drush sql:sync @cloud.prod @self''

  nn-docker-bash:
    desc: Opens a bash shell in the Drupal Docker container
    cmds:
      - docker compose exec -it drupal bash
    interactive: true

  nn-docker-prod-deploy:
    desc: Build container and install codebase on production
    cmds:
      - sudo ./nn/docker-prod/deploy.sh

  nn-docker-prod-first-install:
    desc: Build container and install drupal on the site, drush site install, run only once!
    cmds:
      - sudo ./nn/docker-prod/first_install.sh

  nn-docker-prod-bash:
    desc: Opens a bash shell in the Drupal Docker container
    cmds:
      - docker compose exec -it drupal bash
    interactive: true
