version: '3'

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task -l

  # "Local development helpers"
  nn-lando-start:
    desc: Start coding - composer install, sync db, start lando
    cmds:
      - ./nn/lando/nn_start.sh

  nn-lando-checks:
    desc: Run checks phpcs, phpstan on custom modules
    cmds:
      - ./nn/lando/nn_checks.sh
      
  nn-lando-build-frontend:
    desc: Builds the frontend assets
    cmds:
      - ./nn/lando/nn_build_frontend.sh

  nn-lando-sync-db-prod:
    desc: Syncs the local database with the production database
    cmds:
      - ./nn/lando/nn_sync_db_prod.sh

  nn-lando-maintenance:
    desc: Puts the site into maintenance mode
    cmds:
      - ./nn/lando/nn_maintenance.sh

  # "SSH into"
  nn-ssh-prod:
    desc: SSH into the production server
    aliases: [prod]
    cmds:
      - ssh netnode@prod.example.ch.netnode.cloud
    interactive: true

  nn-ssh-prod-root:
    desc: SSH into the production server
    aliases: [prod-root]
    cmds:
      - ssh root@prod.example.ch.netnode.cloud
    interactive: true

  nn-ssh-stage:
    desc: SSH into the stage server
    aliases: [stage]
    cmds:
      - ssh netnode@stage.example.ch.netnode.cloud
    interactive: true

  nn-ssh-stage-root:
    desc: SSH into the stage server
    aliases: [stage-root]
    cmds:
      - ssh root@stage.example.ch.netnode.cloud
    interactive: true

  # Docker commands (usually used on servers)
  nn-docker-sync-db-prod:
    desc: Syncs the local database with the production database using Docker
    cmds:
      - docker compose exec drupal sh -c 'drush sql:sync @cloud.prod @self''

  nn-docker-bash:
    desc: Opens a bash shell in the Drupal Docker container
    cmds:
      - docker compose exec -it drupal bash
    interactive: true

  nn-docker-prod-deploy:
    desc: Build container and install codebase on production
    cmds:
      - sudo ./nn/docker-prod/deploy.sh

  nn-docker-prod-first-install:
    desc: Build container and install drupal on the site, drush site install, run only once!
    cmds:
      - sudo ./nn/docker-prod/first_install.sh

  # "Open" stuff for easy access
  open-bitbucket:
    desc: Opens Bitbucket repository in browser
    aliases: [bit]
    cmds:
      - open https://bitbucket.org/NETNODEAG/domain.ch

  open-jira:
    desc: Opens the Jira in browser
    aliases: [jira]
    cmds:
      - open https://netnode.atlassian.net/jira/software/c/projects/PROJECT_XYZ

  open-monitoring:
    desc: Opens monitoring websites (zabbix, cloudflare, hcloud)
    aliases: [monitor]
    cmds:
      - open (zabbix link)
      - open (cloudflare link)
      - open (hcloud)
      - open (other monitoring tool)

  # Demo (delete if not a throw away demo)
  nn-demo-install:
    desc: Installs the Drupal demo using PHP server
    cmds:
      - ./nn/demo/nn_demo_install.sh

  nn-demo-serve:
    desc: Serves the Drupal demo using PHP server
    cmds:
      - ./nn/demo/nn_demo_serve.sh